_extends: .github
repository:
  name: is-website-vulnerable
  description: >-
    opinionated scaffolder for testing web-based projects against
    is-website-vulnerable
  homepage: https://npm.im/@form8ion/is-website-vulnerable
  private: false
branches:
  - name: master
    protection: null
rulesets:
  - name: prevent destruction of the default branch
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - ~DEFAULT_BRANCH
        exclude: []
    rules:
      - type: deletion
      - type: non_fast_forward
  - name: verification must pass
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - ~DEFAULT_BRANCH
        exclude: []
    rules:
      - type: required_status_checks
        parameters:
          strict_required_status_checks_policy: false
          required_status_checks:
            - context: workflow-result
              integration_id: 15368
    bypass_actors:
      - actor_id: 3208999
        actor_type: Team
        bypass_mode: always
